def get_stopwords():

    return sorted([
        # "aspx",
        "facebook photo php",
        "facebook photo type",
        "fbid",
        "concord",
        "lerner",
        "page",
        "fbid set",
        "fbid set type",
        "gdata",
        "post",
        "meghan",
        "dubyak",
        "coney",
        "fudge",
        "french",
        "hill",
        "boko",
        "haram",
        "hekmati",
        "lew",
        "cruzcrew",
        "dije",
        "buffalo",
        "sebelius",
        "geithner",
        "bob",
        "king",
        "lee",
        "mas",
        "las",
        "ley",
        "con",
        "dent",
        "orange",
        "west",
        "sarabjit",
        "jagirdar",
        "shinseki",
        "coat",
        "lew",
        "knight",
        "koskinen",
        "tedcruz",
        "hoosier",
        "redding",
        "dije",
        "abedini",
        "flake",
        "gray",
        "concord",
        "blunt",
        "wmata",
        "metro",
        "page",
        "lerner",
        "bishop",
        "lee",
        # "youtube",
        # "http",
        # "html",
        # "http bit",
        # "http goo",
        # "http gov",
        # "http picture",
        # "http picture photo",
        # "http tinyurl",
        # "http usa",
        # "http usa gov",
        # "http www",
        # "http www facebook",
        # "http www youtube",
        # "http youtu",
        "issued following statement",
        "issued following",
        # "org http",
        # "org http www",
        # "pdf",
        # "php",
        # "php fbid",
        # "php fbid set",
        "htsyndication",
        "hindustantimes",
        "content requirement contact editor",
        "respect article",
        "query regarding article",
        "slosberg",
        "contact editorial",
        "content need contact",
        "plusme",
        "nidal",
        "mazen",
        "biscayne",
        "amp",
        "rsquo",
        "ldquo",
        "released following statement",
        "set type",
        "wolf",
        "slaughter",
        "joscelyn",
        "greenwell",
        "rep",
        "sen",
        "young",
        "mar",
        "las",
        "hatch",
        "ted",
        "mark",
        "collins",
        "augusta",
        "lee",
        "manchester",
        "schip",
        "clapper",
        "chuck",
        "todd",
        "que",
        "los",
        "con",
        "bond",
        "por",
        "para",
        "scott",
        "bob",
        "blunt",
        "king",
        "buffalo",
        "geithner",
        "charleston",
        "scalia",
        "esta",
        "chertoff",
        "mas",
        "sus",
        "mark",
        "coat",
        "este",
        "peltier",
        "white",
        "sebelius",
        "house",
        "senate",
        "hunter",
        "senator",
        "representative",
        "representatives",
        "senators",
        "congressman",
        "congresswoman",
        "john",
        "skinner",
        "ron",
        # "https",
        "tom",
        "cotton",
        "bishop",
        "bush",
        "ted",
        "mark",
        "hatch",
        "peron",
        "rodham",
        "clinton",
        "trump",
        "hardy",
        "warner",
        "ben",
        "carson",
        "rand",
        "paul",
        "brook",
        "tammy",
        "david",
        "johnson",
        "wilson",
        "harry",
        "frank",
        "sidle",
        "ricks",
        "goss",
        "fareed",
        "chuck",
        "tanner",
        "hardy",
        "clay",
        "tucker",
        "turner",
        "hues",
        "elan",
        "seaward",
        "cox",
        "demos",
        "duer",
        "cotton",
        "dorian",
        "ray",
        "dickey",
        "weller",
        "singer",
        "cates",
        "cater",
        "parry",
        "sears",
        "ford",
        "reeves",
        "keyes",
        "welles",
        "garrison",
        "james",
        "bush",
        "adam",
        "adams",
        "brown",
        "stallings",
        "hays",
        "raven",
        "waltz",
        "wheeler",
        "eddy",
        "hoover",
        "pease",
        "somer",
        "groves",
        "dykes",
        "homer",
        "leavens",
        "lincoln",
        "brookes",
        "coons",
        "bowles",
        "cook",
        "assad",
        "bill",
        "dent",
        "dutch",
        "burke",
        "virginia",
        "potter",
        "pike",
        "don",
        "carpenter",
        "pierce",
        "franks",
        "archer",
        "shaver",
        "sires",
        "hatch",
        "fanning",
        "marshall",
        "peck",
        "evens",
        "bader",
        "jade",
        "golder",
        "nan",
        "georgia",
        "washington",
        "carmine",
        "crow",
        "curl",
        "jack",
        "boles",
        "kerns",
        "wells",
        "golderer",
        "porter",
        "grimes",
        "poling",
        "lance",
        "skinner",
        "swan",
        "gore",
        "america",
        "bray",
        "hayes",
        "pulles",
        "norman",
        "ruth",
        "baron",
        "reeve",
        "hares",
        "stillings",
        "franker",
        "garland",
        "mark",
        "tuck",
        "rounds",
        "berlin",
        "aurora",
        "akin",
        "carol",
        "nettles",
        "berry",
        "parkes",
        "rice",
        "rick",
        "burr",
        "cooper",
        "napoleon",
        "plough",
        "paris",
        "ariz",
        "frank",
        "sterling",
        "beavers",
        "hay",
        "ham",
        "savannah",
        "jared",
        "crane",
        "ruby",
        "harry",
        "bloom",
        "whang",
        "shepherd",
        "withers",
        "hale",
        "kern",
        "buck",
        "jimmy",
        "august",
        "maness",
        "holmes",
        "cherry",
        "halter",
        "john",
        "canter",
        "ash",
        "borne",
        "rosier",
        "barber",
        "bacon",
        "bates",
        "nyserda",
        "schodack",
        "dominic",
        "honneur",
        "wyo",
        "nev",
        "tex",
        "kugelman",
        "lapierre",
        "teddy",
        "eisenhower",
        "samuels",
        "sheryl",
        "tenn",
        "miss",
        "scheimreif",
        "molly",
        "kayla",
        "bryne",
        "kendra",
        "teele",
        "riaz",
        "seavey",
        "whiterock",
        "coutts",
        "dirksen",
        "sloane",
        "alito",
        "holder",
        "lee",
        "paulison",
        "coat",
        "pat",
        "sonia",
        "mich",
        "wis",
        "moniz",
        "conn",
        "mukasey",
        "pat",
        "bernanke",
        "mont",
        "bob",
        "hammill",
        "drew",
        "first",
        "second",
        "third",
        "fourth",
        "fifth",
        "sixth",
        "seventh",
        "eighth",
        "ninth",
        "tenth",
        "rdquo",
        "hawai",
        "fla",
        "rdquo",
        "mich",
        "issued",
        "released",
        "wash",
        "minn",
        "following"
    ], key=lambda x: len(x), reverse=True)