def get_stopwords():

    return [
        "twitter",
        "facebook",
        "instagram",
        "profile",
        "page",
        "tweet",
        "post",
        "like",
        "share",
        "comment",
        "retweet",
        "fbid",
        "photo",
        "album",
        "event",
        "group",
        "live",
        "video",
        "youtube",
        "insta",
        "tiktok",
    ]
