# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='qualification_assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='django_learning.QualificationAssignment'),
        ),
        migrations.AlterField(
            model_name='code',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='django_learning.Assignment'),
        ),
    ]
