# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_learning', '0003_load_liwc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='external_link',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
