# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_learning', '0004_label_pointers'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='external_link',
            field=models.URLField(null=True),
        ),
    ]
