# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("django_learning", "0006_auto_20170411_1544")]

    operations = [
        migrations.AddField(
            model_name="question",
            name="optional",
            field=models.BooleanField(default=False),
        )
    ]
