# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_learning', '0007_question_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dependency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='django_learning.Label'),
        ),
    ]
