# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_learning', '0008_question_dependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='turk_approved',
            field=models.BooleanField(default=False),
        ),
    ]
