# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_learning', '0009_assignment_turk_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificationmodel',
            name='num_cores',
        ),
        migrations.AddField(
            model_name='classificationmodel',
            name='probability_threshold',
            field=models.FloatField(default=None, null=True),
        ),
    ]
