# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("django_learning", "0010_auto_20171108_1042")]

    operations = [
        migrations.AlterField(
            model_name="hittype", name="name", field=models.CharField(max_length=50)
        )
    ]
