# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [("django_learning", "0014_auto_20171113_1701")]

    operations = [
        migrations.AddField(
            model_name="topicmodel",
            name="name",
            field=models.CharField(default=b"w29_life", max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name="topicmodel",
            name="parameters",
            field=picklefield.fields.PickledObjectField(
                editable=False,
                help_text=b"A pickle file of the parameters used",
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(name="topicmodel", unique_together=set([])),
        migrations.RemoveField(model_name="topicmodel", name="anchor_strength"),
        migrations.RemoveField(model_name="topicmodel", name="num_topics"),
        migrations.RemoveField(model_name="topicmodel", name="sample_size"),
    ]
