# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-08 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("django_learning", "0017_auto_20171115_1012")]

    operations = [
        migrations.AddField(
            model_name="code", name="notes", field=models.TextField(null=True)
        ),
        migrations.AddField(
            model_name="question",
            name="show_notes",
            field=models.BooleanField(default=False),
        ),
    ]
