# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-04-04 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_learning', '0019_auto_20190130_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sandbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qualificationtest',
            name='sandbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='qualificationtest',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('name', 'sandbox')]),
        ),
        migrations.AlterUniqueTogether(
            name='qualificationtest',
            unique_together=set([('name', 'sandbox')]),
        ),
    ]
