# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("django_learning", "0021_auto_20190408_1541")]

    operations = [
        migrations.RenameField(
            model_name="classificationmodel",
            old_name="cache_hash",
            new_name="model_cache_hash",
        ),
        migrations.AddField(
            model_name="classificationmodel",
            name="dataset_cache_hash",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
