# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-22 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_learning', '0023_classificationmodel_test_dataset_cache_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sandbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qualificationtest',
            name='sandbox',
            field=models.BooleanField(default=False),
        ),
    ]
