# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-15 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_learning', '0026_hit_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hittype',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
