# Generated by Django 2.2.6 on 2019-12-17 08:36

from django.db import migrations, models
import django.db.models.deletion


def migrate_hit_types_forward(apps, schema_editor):
    Sample = apps.get_model('django_learning', 'Sample')
    HIT = apps.get_model('django_learning', 'HIT')
    for hit in HIT.objects.all():
        hit.hit_type = hit.sample.hit_type
        hit.save()

def migrate_hit_types_backward(apps, schema_editor):
    Sample = apps.get_model('django_learning', 'Sample')
    HIT = apps.get_model('django_learning', 'HIT')
    for hit in HIT.objects.all():
        hit.sample.hit_type = hit.hit_type
        hit.sample.save()

class Migration(migrations.Migration):

    dependencies = [
        ('django_learning', '0026_hit_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='hit_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hits',
                                    to='django_learning.HITType'),
        ),
        migrations.RunPython(
            migrate_hit_types_forward,
            migrate_hit_types_backward
        ),
        migrations.RemoveField(
            model_name='sample',
            name='hit_type',
        ),
    ]
