# Generated by Django 3.1.2 on 2020-10-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_learning', '0027_auto_20191217_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfragment',
            name='scope',
            field=models.JSONField(default=dict, help_text='A dictionary of filter parameters for defining documents within which the fragment can exist'),
        ),
        migrations.AlterField(
            model_name='hit',
            name='finished',
            field=models.BooleanField(null=True),
        ),
    ]
