# Generated by Django 3.1.2 on 2021-12-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_learning', '0029_auto_20210831_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='sandbox',
            new_name='mturk_sandbox',
        ),
        migrations.RenameField(
            model_name='qualificationtest',
            old_name='sandbox',
            new_name='mturk_sandbox',
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='qualificationtest',
            unique_together={('name', 'mturk_sandbox')},
        ),
    ]
