# Generated by Django 3.1.2 on 2021-12-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_learning', '0030_auto_20211210_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mturk_sandbox',
            field=models.BooleanField(default=True),
        ),
    ]
